---
version: "3"

services:
  apt_cache:
    # build: .
    # build: /docker/docker-compose/apt-cache/
    image: sameersbn/apt-cacher-ng
    ports:
      - 3142:3142
    volumes:
      - /docker/docker-compose/apt-cache/cache:/var/cache/apt-cacher-ng
